version: '3'

services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: cast-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - '${DB_PORT:-3306}:3306'
    networks:
      - cast-network

volumes:
  mysql-data:

networks:
  cast-network:
    driver: bridge
